# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='desc',
            field=models.TextField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
